### ISSUE TITLE
sourcepawn grammar bnf 

### ISSUE THREAD

**Issue by ghost** [collinsmith/intellij-sourcepawn#1]
could you publish the bnf grammar file for sourcepawn?

**Comment by collinsmith** [comment]
There isn't one. [This](https://github.com/collinsmith/intellij-sourcepawn/tree/master/src/main/java/net/alliedmods/lang/sourcepawn/lexer) package contains the grammars that were written `*.flex`, but they are my own and not 100% tested.

**Comment by ghost** [comment]
thanks
